# Generated by Django 3.1.3 on 2020-11-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_items', '0002_auto_20201105_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
