# Generated by Django 3.1.3 on 2020-11-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_annotation_is_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='priority',
            field=models.PositiveSmallIntegerField(verbose_name='Proridade'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Título'),
        ),
    ]
