# Generated by Django 3.1.3 on 2021-01-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_auto_20201118_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Título'),
        ),
    ]
